// Selected UI copy from the reference dapp; kept local for portable builds.
export const referenceEn = {
  modalCreateTitle: "Create Trade Account",
  modalCreateDescription:
    "Get HYPE gas, then sign to create your LeverAcc smart account.",
  modalDepositTitle: "Deposit to Fund Account",
  modalDepositDescription:
    "Move USDC into your Fund Account on HyperEVM from Arbitrum or HyperCore.",
  modalBorrowTitle: "Quick Borrow",
  modalRepayTitle: "Repay Account Debt",
  modalTransferTitle: "Account Transfer",
  modalWithdrawTitle: "Withdraw USDC to Arbitrum",
  withdrawSubtitle:
    "Withdraw from your Trade or Fund account to your Fund account on Arbitrum. Bridge fees are deducted from the amount.",
  transferDescription:
    "Move USDC between your Fund wallet on HyperEVM and your LA Trade Account.",
  depositWarning:
    "External deposits start with USDC on Arbitrum. Hyperliquid deposits use USDC from HyperCore. The destination is your Fund Account.",
  connectedAccount: "Fund Account · connected",
  externalWallet: "External Deposit",
  poweredCircle: "Powered by Circle CCTP",
  gasStep: "Get HYPE Gas",
  gasReady: "HYPE gas is available in your wallet",
  signCreate: "Sign & Create Account",
  createDescription:
    "Once gas is available, sign to create your Trade Account.",
  accountCreated:
    "Your Trade Account has been created. Continue to fund your account.",
  fundLabel: "Fund Account",
  tradeLabel: "Trade Account",
  borrowAction: "Borrow USDC",
  depositAction: "Deposit USDC",
  withdrawAction: "Withdraw USDC",
  repayAction: "Confirm Repay",
  transferToTrade: "Transfer to Trade Account",
  transferToFund: "Transfer to Fund Account",
  receiveLabel: "You receive",
  feeLabel: "Fee",
  time: "Est. time",
  repayOriginal: "Original Amount",
  repayPrincipal: "Outstanding Principal",
  repayInterest: "Accrued Interest",
  repayTotal: "Total to Repay",
  repayAmount: "Account-level repay amount (USDC)",
  repayHint:
    "This repays account-level debt on-chain. The selected row is only used to suggest a default amount and does not guarantee that one specific borrow lot is closed by itself.",
  routeFrom: "From",
  routeTo: "To",
  withdrawFundLabel: "Fund Account",
  withdrawTradeLabel: "Trade Account",
  withdrawTime: "After network confirmation",
  withdrawDirectNote:
    "LA → Arbitrum directly. Sign the withdrawal intent and source transaction; pay source gas in HYPE. Core funds must first return to LA on HyperEVM.",
  withdrawFeeLabel: "Maximum fee",
  capacity: "Available to Borrow",
};
export const referenceZh = {
  modalCreateTitle: "创建交易账户",
  modalCreateDescription: "获取 HYPE Gas，然后签名创建 LeverAcc 智能账户。",
  modalDepositTitle: "存入资金账户",
  modalDepositDescription:
    "从 Arbitrum 或 HyperCore 将 USDC 存入您在 HyperEVM 上的资金账户。",
  modalBorrowTitle: "快速借入",
  modalRepayTitle: "偿还账户债务",
  modalTransferTitle: "账户转账",
  modalWithdrawTitle: "提取 USDC 至 Arbitrum",
  withdrawSubtitle:
    "从交易账户或资金账户提现至本人 Arbitrum 上的资金账户。跨链费用将从提现金额中扣除。",
  transferDescription: "在 HyperEVM 资金账户与 LA 交易账户之间转移 USDC。",
  depositWarning:
    "外部入金使用 Arbitrum 上的 USDC；Hyperliquid 入金使用 HyperCore 上的 USDC。目标为您的资金账户。",
  connectedAccount: "资金账户 · 已连接",
  externalWallet: "外部充值",
  poweredCircle: "由 Circle CCTP 提供支持",
  gasStep: "获取 HYPE Gas",
  gasReady: "钱包中的 HYPE Gas 已充足",
  signCreate: "签名并创建账户",
  createDescription: "Gas 充足后，签名创建交易账户。",
  accountCreated: "交易账户已创建，可以继续下一步充值。",
  fundLabel: "资金账户",
  tradeLabel: "交易账户",
  borrowAction: "借入 USDC",
  depositAction: "存入 USDC",
  withdrawAction: "提取 USDC",
  repayAction: "确认还款",
  transferToTrade: "转入交易账户",
  transferToFund: "转入资金账户",
  receiveLabel: "预计收到",
  feeLabel: "手续费",
  time: "预计时间",
  repayOriginal: "原始金额",
  repayPrincipal: "未还本金",
  repayInterest: "累计利息",
  repayTotal: "应还总额",
  repayAmount: "账户级还款金额（USDC）",
  repayHint:
    "此操作偿还链上账户级债务。所选记录仅用于建议默认金额，不保证单独结清某一笔借款。",
  routeFrom: "转出",
  routeTo: "转入",
  withdrawFundLabel: "资金账户",
  withdrawTradeLabel: "交易账户",
  withdrawTime: "等待网络确认",
  withdrawDirectNote:
    "LA 直接提现到 Arbitrum：需签署提现意图和源链交易，并支付 HYPE gas；Core 资金需先回到 LA 的 HyperEVM 余额。",
  withdrawFeeLabel: "最高费用",
  capacity: "可借额度",
};
