import { referenceEn, referenceZh } from "./referenceStrings";
export const en = {
  fundToArbitrum: "Fund → Arbitrum",
  coreDepositRoute: "HyperCore → Fund",
  recommended: "Recommended",
  selectSource: "Withdrawal source",
  mainnetOnly: "Arbitrum withdrawals are available on mainnet only.",
  transferLayers: "Other account transfers",
  poweredCore: "Powered by Hyperliquid",

  repayCoreAvailable: "Core available",
  repayAccountEvm: "Account EVM",
  repayRealtimeDebt: "Realtime debt",
  repayAvailable: "Available to repay",
  repayCurrentBorrowed: "Current Borrowed",
  collateral: "Collateral",
  tradingAvailable: "Available to trade",
  borrowed: "Borrowed",
  riskIndex: "Risk index",
  riskBasis: "Debt / net value",
  tradingHint:
    "Spot USDC total less held balance. A zero balance does not fall back to Perps.",
  riskHint:
    "Debt / account net value. This is a debt ratio, not a liquidation threshold.",
  withdrawDescription:
    "Withdraw USDC from Trade to your connected owner wallet.",
  destinationNetwork: "Destination network",
  withdrawable: "Withdrawable",
  mandatoryReturn: "Debt returned",
  withdrawFees: "Protocol & gas fees",
  withdrawSteps:
    "If needed, move Core Spot funds to Trade EVM first. Keep 0.005 USDC on Core. Review proceeds, then confirm each step in your wallet.",
  viewWithdrawal: "View withdrawal progress",
  continueWithdrawal: "Continue withdrawal",
  withdrawArbitrumSteps:
    "Core funds move to Trade EVM when needed. Confirm each step in your wallet; the bridge step ends when its transaction is submitted.",
  withdrawalLocked:
    "The next step is available on this page. Continuing checks current prerequisites.",

  completeSetup: "Complete account setup",
  topUpGas: "Fund network gas",
  gasFundingDescription:
    "To create your account, send {amount} USDC on {source} for HYPE gas.",
  gasFundingSign: "Sign & Swap {amount} USDC for Gas",
  gasFundingInfo:
    "Your {amount} USDC transfer is processed by the Gas Station and HYPE is returned to your wallet.",
  gasFundingPending: "Waiting for HYPE to arrive. Do not send again.",
  creationPending:
    "Creating your trading account. Waiting for on-chain confirmation…",
  gasFundingSigning: "Confirming your {source} USDC transfer...",
  tradingAccount: "Trading Account",
  gasRequired:
    "Send at least 0.01 HYPE to this owner address on HyperEVM, then refresh.",
  done: "Done",
  balance: "Balance",
  reverse: "Reverse direction",
  borrowRatio: "Borrow ratio",
  minimumBorrow: "Minimum borrow",
  fundToTrade: "Fund → Trade",
  accountToFund: "Trade → Fund",
  awaitingAction: "Ready for next step",
  continueTransfer: "Continue transfer",
  activationNote:
    "First Core activation deducts 1 USDC. Keep 1.005 USDC in owner Core for the relay.",
  approval: "Approve USDC",
  depositStep: "Deposit to Core",
  relay: "Forward to Trade",
  topup: "Move Core funds to EVM",
  withdraw: "Withdraw",
  copy: "Copy address",
  copied: "Copied",
  close: "Close",
  closeBusy: "Wait for the current wallet operation to finish before closing.",
  status: "Status",
  viewProgress: "View transfer progress",
  noFeatures: "No actions enabled.",
  transferLocked:
    "The next step is available on this page. Continuing checks current prerequisites.",
  title: "Account & lending",
  subtitle: "LEVERACC",
  mainnet: "Mainnet",
  testnet: "Testnet",
  borrow: "Borrow",
  repay: "Repay",
  deposit: "Deposit",
  transfer: "Transfer",
  fund: "Fund",
  evm: "Trade EVM",
  spot: "Core Spot",
  perps: "Perps",
  debt: "Outstanding debt",
  usdc: "USDC",
  connect: "Connect wallet",
  disconnected: "Connect a wallet in the host application to get started.",
  signIn: "Sign a message to access your LeverAcc account.",
  create: "Create Trading Account",
  noAccount:
    "Your wallet is connected. Create a Trading Account to deposit collateral and borrow.",
  collateralBreakdown: "Collateral breakdown",
  loading: "Reading account…",
  amount: "Amount",
  max: "Max",
  source: "From",
  destination: "To",
  route: "Transfer route",
  review: "Review",
  confirm: "Confirm in wallet",
  back: "Back",
  cancel: "Cancel",
  setupTitle: "Account setup required",
  setupBody:
    "Complete the indicated steps in the host application, then refresh here.",
  projectMismatch: "This Trading Account belongs to another project.",
  switchProject: "Switch project",
  switchInfo:
    "Switching may invalidate the existing trading authorization. Your host application will need to authorize this account again.",
  currentProject: "Current project",
  targetProject: "Target project",
  account: "Trading Account",
  owner: "Owner wallet",
  fundRoute: "Fund → Trade EVM",
  arbitrumRoute: "Arbitrum → Fund",
  evmToCore: "Trade EVM → Core Spot",
  coreToEvm: "Core Spot → Trade EVM",
  spotToPerps: "Core Spot → Perps",
  perpsToSpot: "Perps → Core Spot",
  tradeToFund: "Trade EVM → Fund",
  tradeToArbitrum: "Trade EVM → Arbitrum",
  arbUnavailable:
    "Direct Arbitrum withdrawal is unavailable for this deployment.",
  quote: "Get bridge quote",
  fee: "Maximum bridge fee",
  receive: "Minimum received",
  gas: "Network gas is paid separately in the source-chain native asset.",
  approve: "Approve USDC",
  bridge: "Bridge USDC",
  preparing: "Preparing",
  signing: "Waiting for signature",
  submitting: "Confirm transaction in wallet",
  refreshStatus: "Refresh status",
  submitted: "Transaction submitted",
  confirming: "Confirming transaction",
  bridging: "Waiting for destination chain",
  settling: "Waiting for funds to arrive",
  success: "Completed",
  failed: "Failed",
  viewTransaction: "View transaction",
  viewDestination: "View destination transaction",
  pending: "Confirm the current request in your wallet.",
  borrowNote:
    "Borrowed USDC arrives in Trade EVM. Transfer it to Core Spot when you are ready.",
  repayNote:
    "Repayment uses Trade EVM USDC. Move funds from Core first if needed.",
  depositNote: "Deposit USDC into your Trading Account to fund your account.",
  bridgeNote:
    "Arbitrum deposits arrive in your Fund wallet on HyperEVM. Then deposit into Trade EVM.",
  reviewTitle: "Review transaction",
  noBalance: "Balance unavailable",
  invalidAmount: "Enter a positive amount with up to 6 decimals.",
  dailyRate: "Current daily rate",
  rateNote: "The rate is variable. Review the current rate before each borrow.",
  term: "Borrow term",
  days: "days",
  coreFee: "Maximum Core return fee",
  allDebtNote:
    "Includes a 0.1% authorization buffer for accruing interest. The contract limits payment to live debt.",
  footer: "Powered by LeverAcc",
  notReady: "Account information is unavailable. Refresh before continuing.",
  ...referenceEn,
};
export type TextKey = keyof typeof en;
export const zh: Record<TextKey, string> = {
  fundToArbitrum: "Fund → Arbitrum",
  coreDepositRoute: "HyperCore → Fund",
  recommended: "推荐",
  selectSource: "提现来源",
  mainnetOnly: "Arbitrum 提现仅支持主网。",
  transferLayers: "其他账户划转",
  poweredCore: "由 Hyperliquid 提供支持",

  repayCoreAvailable: "Core 可用",
  repayAccountEvm: "账户 EVM",
  repayRealtimeDebt: "实时债务",
  repayAvailable: "可还金额",
  repayCurrentBorrowed: "当前已借",
  collateral: "抵押品",
  tradingAvailable: "可用交易余额",
  borrowed: "借款",
  riskIndex: "风险指数",
  riskBasis: "债务 / 净资产",
  tradingHint: "Spot USDC 总余额减去冻结余额；余额为零时不回退到 Perps。",
  riskHint: "债务 ÷ 账户净资产值。此项为负债比例，不是清算阈值。",
  withdrawDescription: "将 Trade 中的 USDC 提现至当前连接的主钱包。",
  destinationNetwork: "到账网络",
  withdrawable: "可提现",
  mandatoryReturn: "偿还债务",
  withdrawFees: "协议及 Gas 费用",
  withdrawSteps:
    "EVM 余额不足时先从 Core Spot 补足，Core 保留 0.005 USDC。核对预计到账后，依次在钱包确认各步骤。",
  viewWithdrawal: "查看提现进度",
  continueWithdrawal: "继续提现",
  withdrawArbitrumSteps:
    "需要时先将 Core 资金转入 Trade EVM，再逐步在钱包确认；跨链交易发出后即可退出。",
  withdrawalLocked: "下一步仅保留在当前页面，点击继续时会检查实时条件。",

  completeSetup: "完成账户设置",
  topUpGas: "补充网络 Gas",
  gasFundingDescription:
    "创建账户前，在 {source} 转账 {amount} USDC 以获取 HYPE Gas。",
  gasFundingSign: "签名并兑换 {amount} USDC 获取 Gas",
  gasFundingInfo:
    "你的 {amount} USDC 转账将由 Gas Station 处理，HYPE 会返回你的钱包。",
  gasFundingPending: "正在等待 HYPE 到账，请勿重复转账。",
  creationPending: "正在创建交易账户，等待链上确认…",
  gasFundingSigning: "正在确认 {source} USDC 转账…",
  tradingAccount: "交易账户",
  gasRequired:
    "请在 HyperEVM 网络向以下主钱包地址转入至少 0.01 HYPE，然后刷新。",
  done: "完成",
  balance: "余额",
  reverse: "切换方向",
  borrowRatio: "借款比例",
  minimumBorrow: "最低借款额",
  fundToTrade: "资金账户 → 交易账户",
  accountToFund: "交易账户 → 资金账户",
  awaitingAction: "可继续下一步",
  continueTransfer: "继续划转",
  activationNote:
    "首次激活 Core 扣除 1 USDC；主钱包 Core 需保留 1.005 USDC 用于中转。",
  approval: "授权 USDC",
  depositStep: "充值至 Core",
  relay: "转入交易账户",
  topup: "Core 回款至 EVM",
  withdraw: "提现",
  copy: "复制地址",
  copied: "已复制",
  close: "关闭",
  closeBusy: "请等待当前钱包操作结束后再关闭。",
  status: "状态",
  viewProgress: "查看划转进度",
  noFeatures: "暂无已启用功能。",
  transferLocked: "下一步仅保留在当前页面，点击继续时会检查实时条件。",
  title: "账户与借贷",
  subtitle: "LEVERACC",
  mainnet: "主网",
  testnet: "测试网",
  borrow: "借款",
  repay: "还款",
  deposit: "充值",
  transfer: "划转",
  fund: "资金账户",
  evm: "交易账户 EVM",
  spot: "Core 现货",
  perps: "永续账户",
  debt: "当前负债",
  usdc: "USDC",
  connect: "连接钱包",
  disconnected: "请先在接入方应用中连接钱包。",
  signIn: "签署登录消息以访问 LeverAcc 账户。",
  create: "创建交易账户",
  noAccount: "钱包已连接。创建交易账户后即可充值抵押品并借款。",
  collateralBreakdown: "抵押品金额分布",
  loading: "正在读取账户…",
  amount: "金额",
  max: "最大",
  source: "从",
  destination: "至",
  route: "划转路径",
  review: "查看详情",
  confirm: "在钱包中确认",
  back: "返回",
  cancel: "取消",
  setupTitle: "账户尚需完成设置",
  setupBody: "请在接入方应用中完成以下步骤，然后在此刷新。",
  projectMismatch: "该交易账户已绑定其他项目。",
  switchProject: "切换项目",
  switchInfo: "切换可能使现有交易授权失效，接入方应用需要重新授权该账户。",
  currentProject: "当前项目",
  targetProject: "目标项目",
  account: "交易账户",
  owner: "主钱包",
  fundRoute: "资金账户 → 交易账户 EVM",
  arbitrumRoute: "Arbitrum → 资金账户",
  evmToCore: "交易账户 EVM → Core 现货",
  coreToEvm: "Core 现货 → 交易账户 EVM",
  spotToPerps: "Core 现货 → 永续账户",
  perpsToSpot: "永续账户 → Core 现货",
  tradeToFund: "交易账户 EVM → 资金账户",
  tradeToArbitrum: "交易账户 EVM → Arbitrum",
  arbUnavailable: "当前部署未开放直接提现至 Arbitrum。",
  quote: "获取跨链报价",
  fee: "跨链费用上限",
  receive: "最低到账",
  gas: "网络 Gas 另以来源链原生资产支付。",
  approve: "授权 USDC",
  bridge: "跨链转入 USDC",
  preparing: "准备中",
  signing: "等待签名",
  submitting: "请在钱包中确认交易",
  refreshStatus: "刷新状态",
  submitted: "交易已发出",
  confirming: "等待交易确认",
  bridging: "等待目标链确认",
  settling: "等待资金到账",
  success: "已完成",
  failed: "失败",
  viewTransaction: "查看交易",
  viewDestination: "查看目标链交易",
  pending: "请在钱包中确认当前请求。",
  borrowNote: "借入的 USDC 将到账交易账户 EVM，可随后划转至 Core 现货。",
  repayNote: "使用交易账户 EVM 的 USDC 还款，余额不足时请先从 Core 划转。",
  depositNote: "向交易账户充值 USDC 以补充资金。",
  bridgeNote: "Arbitrum 充值先到达 HyperEVM 资金账户，再充值至交易账户 EVM。",
  reviewTitle: "确认交易详情",
  noBalance: "余额暂不可用",
  invalidAmount: "请输入正数金额，最多 6 位小数。",
  dailyRate: "当前日利率",
  rateNote: "利率为浮动利率，每次借款前请查看当前利率。",
  term: "借款期限",
  days: "天",
  coreFee: "Core 回款费用上限",
  allDebtNote: "包含 0.1% 的利息授权缓冲，合约按实时负债限制实际还款额。",
  footer: "由 LeverAcc 提供支持",
  notReady: "账户信息暂不可用，请刷新后继续。",
  ...referenceZh,
};
const reasons: Record<string, [string, string]> = {
  PROJECT_BINDING_REQUIRED: ["Project binding required", "需要绑定项目"],
  REGISTRATION_REQUIRED: [
    "Register the account in the host application",
    "请在接入方注册账户",
  ],
  EXECUTION_AUTHORIZATION_REQUIRED: [
    "Trading wallet authorization required",
    "需要交易钱包授权",
  ],
  EXECUTION_AUTHORIZATION_EXPIRED: [
    "Trading wallet authorization expired",
    "交易钱包授权已过期",
  ],
  AUTHORIZATION_CONFIRMATION_REQUIRED: [
    "Confirm authorization in the host application",
    "请在接入方确认授权",
  ],
  RISK_WALLET_REQUIRED: [
    "Project risk wallet configuration required",
    "项目方需要配置风险钱包",
  ],
  CORE_ACTIVATION_REQUIRED: ["Activate the Core account", "需要激活 Core 账户"],
  CORE_AUTHORIZATION_REQUIRED: [
    "Renew or confirm Core authorization",
    "需要更新或确认 Core 授权",
  ],
};
export function reasonText(reason: string, locale: "en" | "zh") {
  return (
    reasons[reason]?.[locale === "zh" ? 1 : 0] ??
    (locale === "zh"
      ? `协议暂不允许借款（${reason.replace("BORROW_BLOCKED_", "")}）`
      : `Protocol borrowing is blocked (${reason.replace("BORROW_BLOCKED_", "")})`)
  );
}
