import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
const root = resolve(import.meta.dirname, "..");
for (const name of [
  "ILeverAccAccount",
  "ILeverAccAccountFactory",
  "ILeverAccRegistry",
  "ILeverAccEconomicConfig",
  "ILeverAccFundVaultManager",
  "ILeverAccL1ReadAdapter",
  "IERC20",
  "ICoreDepositWalletLike",
]) {
  const source = resolve(
    root,
    "../leveracc-hyperevm-protocol",
    ["IERC20", "ICoreDepositWalletLike"].includes(name)
      ? `out/${name}.sol/${name}.json`
      : `abi/${name}.json`,
  );
  const raw = JSON.parse(await readFile(source, "utf8"));
  const abi = Array.isArray(raw) ? raw : raw.abi;
  if (!Array.isArray(abi)) throw new Error(`Invalid ABI: ${source}`);
  await mkdir(resolve(root, "src/abi"), { recursive: true });
  await writeFile(
    resolve(root, `src/abi/${name}.ts`),
    `// Synced from leveracc-hyperevm-protocol; run pnpm abi:sync.\nexport const ${name}ABI = ${JSON.stringify(abi)} as const;\n`,
  );
}
// Derive withdrawal EIP-712 field order from the protocol ABI alongside its TS types.
const accountAbi = JSON.parse(
  await readFile(
    resolve(root, "../leveracc-hyperevm-protocol/abi/ILeverAccAccount.json"),
    "utf8",
  ),
);
let withdrawal =
  '// Generated by pnpm abi:sync. Do not edit.\nimport type { ContractFunctionArgs, TypedData } from "viem";\nimport type { ILeverAccAccountABI } from "../ILeverAccAccount";\n';
for (const [name, fn] of [
  ["WithdrawIntent", "withdraw"],
  ["WithdrawEvmToCoreIntent", "withdrawEvmToCore"],
  ["WithdrawToArbitrumIntent", "withdrawToArbitrum"],
]) {
  const input = accountAbi.find(
    (item) => item.type === "function" && item.name === fn,
  )?.inputs[0];
  if (!input?.components) throw new Error(`Missing protocol intent ${fn}`);
  withdrawal += `export type ${name} = ContractFunctionArgs<typeof ILeverAccAccountABI, "nonpayable", "${fn}">[0];\nexport const ${name}Types = ${JSON.stringify({ [name]: input.components.map(({ name, type }) => ({ name, type })) })} as const satisfies TypedData;\n`;
}
await writeFile(
  resolve(root, "src/abi/generated/WithdrawalTypes.ts"),
  withdrawal,
);
